# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StrategyOutputWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StrategyOutputWindow(object):
    def setupUi(self, StrategyOutputWindow):
        StrategyOutputWindow.setObjectName("StrategyOutputWindow")
        StrategyOutputWindow.resize(1291, 805)
        self.centralwidget = QtWidgets.QWidget(StrategyOutputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StrategyOutput_tablewidget = QtWidgets.QTableWidget(self.centralwidget)
        self.StrategyOutput_tablewidget.setGeometry(QtCore.QRect(0, 0, 1291, 791))
        self.StrategyOutput_tablewidget.setObjectName("StrategyOutput_tablewidget")
        self.StrategyOutput_tablewidget.setColumnCount(0)
        self.StrategyOutput_tablewidget.setRowCount(0)
        StrategyOutputWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StrategyOutputWindow)
        self.statusbar.setObjectName("statusbar")
        StrategyOutputWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StrategyOutputWindow)
        QtCore.QMetaObject.connectSlotsByName(StrategyOutputWindow)

    def retranslateUi(self, StrategyOutputWindow):
        _translate = QtCore.QCoreApplication.translate
        StrategyOutputWindow.setWindowTitle(_translate("StrategyOutputWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StrategyOutputWindow = QtWidgets.QMainWindow()
    ui = Ui_StrategyOutputWindow()
    ui.setupUi(StrategyOutputWindow)
    StrategyOutputWindow.show()
    sys.exit(app.exec_())
